### ISSUE TITLE
blacklist metop-A IASI channels 

### ISSUE THREAD

**Issue by lbi2018** [hafs-community/HAFS#104]
Updating satinfo file to turn off metop-A IASI channels

**Comment by lbi2018** [comment]
/mnt/lfs4/HFIP/hwrfv3/Role.rthmon-ens/hafsv0p2d_2021rt_v01/parm/analysis/gsi/hafs_satinfo.txt is the updated satinfo file

**Comment by BinLiu-NOAA** [comment]
Thanks, @lbi2018! And could you please create a PR and merge this change back to HAFS develop branch? Thanks!
