### ISSUE TITLE
Add the fms2_io_nml namelist section with netcdf_default_format of netcdf4 in input*.nml 

### ISSUE THREAD

**Issue by BinLiu-NOAA** [hafs-community/HAFS#117]
## Description
Add the fms2_io_nml namelist section with netcdf_default_format of netcdf4 in input*.nml 
&fms2_io_nml
netcdf_default_format="netcdf4"
/
Otherwise, the default was the NetCDF "64-bit offset" version, which has issues to support large files.

Note: This information is from the RRFS application team (Eric Rogers) with the suggestion from @bensonr.

## Proposed solution
Add the above-mentioned namelist section in the input*.nml files for the forecast job (ufs-weather-model).

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- addressed by hafs-community/hafs/pull/<pr_number>

**Comment by bensonr** [comment]
The fms2-io default is the older NetCDF "64-bit offset" version.

**Comment by BinLiu-NOAA** [comment]
@bensonr, Thanks for the information! I have updated the description accordingly.
