### ISSUE TITLE
Update DTC co-code-owner for HAFS application repository

### ISSUE THREAD

**Issue by BinLiu-NOAA** [hafs-community/HAFS#146]
## Description
Provide a clear and concise description of the requested feature/capability.
Since @evankalina left DTC, we will need someone to back fill his co-code-owner role for HAFS application repository.

## Proposed solution
How should the new feature/capability be added? If you have thoughts on the implementation strategy, please share them here.
@KathrynNewman agrees that @panll can back fill this role. With that, a PR is needed to update the CODEOWNERS file:
https://github.com/hafs-community/HAFS/blob/develop/.github/CODEOWNERS

## Status (optional)
Do you (or a colleague) plan to work on adding this feature?

## Related to (optional)
Directly reference any related issues or PRs in this or other repositories, and describe how they are related. Examples:
- fixed by hafs-community/hafs/pull/148

**Comment by BinLiu-NOAA** [comment]
@KathrynNewman, @panll, could one of you create a PR to update the CODEOWNERS files accordingly? Thanks!

P.S., I have updated that @panll is one of the [hafs-community](https://github.com/hafs-community)'s co-owners.

**Comment by panll** [comment]
PR is submitted. @BinLiu-NOAA @KathrynNewman
