### ISSUE TITLE
launch failed when setting regional_esg=no

### ISSUE THREAD

**Issue by mlaurako** [hafs-community/HAFS#212]
## Description
We tried running the ESG off (gnomonic grid only) but the workflow failed at launch. We are curious about if it is possible to run without the ESG grid? Thanks!

### To Reproduce:
Machine: Orion
- find a configuration file for any successful run
- set regional_esg to no in config file 
- run rocoto
- then it fails immediately at launch 

## Output (optional)
produtil.prog.ExitStatusException: batchexe('/work/noaa/aoml-hafs1/mko/HAFS/hafsv1_basin/exec/hafs_make_hgrid.x')['--grid_type gnomonic_ed --nlon','1536','--grid_name','C768_grid','--do_schmidt --stretch_factor','1.0001','--target_lon','-79.0','--target_lat','16.4','--nest_grids','1','--parent_tile','6','--istart_nest','49','--jstart_nest','519','--iend_nest','1488','--jend_nest','1018','--halo 0 --great_circle_algorithm']: non-zero exit status (returncode=2)

**Comment by BijuThomas-NOAA** [comment]
@mlaurako This issue is addressed here: [Issue 205](https://github.com/hafs-community/HAFS/issues/205)

**Comment by BinLiu-NOAA** [comment]
Close this issue since it has been addressed by PR #206.
