### ISSUE TITLE
Edit HAFS Documentation

### ISSUE THREAD

**Issue by gspetro-NOAA** [hafs-community/HAFS#220]
## Description
Before merging the feature/hafs_docs branch into develop, the documentation would benefit from additional edits to align it with documentation practices in UFS repositories. 

## Proposed solution
A PR to reorganize the content, provide general edits, and update image file hosting. 

## Status (optional)
I am working on a PR to do this. :)

**Comment by BinLiu-NOAA** [comment]
Close this issue upon PR #221.
