### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [hafs-community/HAFS#268]
I suggest adding the topics `hurricane`, `weather`, `nwp` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by BinLiu-NOAA** [comment]
@Beliavsky Thanks for the suggestion! We went ahead and added "hurricane", "tropical-cyclone" and "numerical-weather-prediction" as related HAFS GitHub repository topics.
