### ISSUE TITLE
Check and update HAFS grib2 products

### ISSUE THREAD

**Issue by BinLiu-NOAA** [hafs-community/HAFS#42]
Check and compare HAFS grib2 output fields with those from HWRF as well as those from GFS and FV3CAM. Since HAFS is FV3 based, we may or may not be able to output every field as from HWRF. Also, we may try to follow GFS for those fields common to GFS and HAFS.

**Comment by BinLiu-NOAA** [comment]
Note: Need to check if we need to add the o3mr variable in the grib2 output for HAFS. The o3mr variable does exist in GFS grib2 output. Potentially, when using grib2 files to initialize an FV3 forecast model, o3mr may also be useful/needed.

**Comment by ZhanZhang-NOAA** [comment]
> Note: Need to check if we need to add the o3mr variable in the grib2 output for HAFS. The o3mr variable does exist in GFS grib2 output. Potentially, when using grib2 files to initialize an FV3 forecast model, o3mr may also be useful/needed.

I don't think it's necessary to include o3mr variable in the HAFS grib2 output. 1. o3mr is not needed for TC diagnostics and has no downstream users at least for now. 2. we will not use HAFS grid2 output to initialize HAFS forecast.
