### ISSUE TITLE
Failed to recurse into submodule path 'sorc/hafs_gsi.fd'

### ISSUE THREAD

**Issue by lliu1220** [hafs-community/HAFS#47]
I'm trying to 
git clone  --recursive https://github.com/hafs-community/HAFS

But I ran into following error, I wonder if someone could give me access to this repo, if this is the problem, thanks:

Cloning into '/work/noaa/marine/lliu/runs/deb/HAFS/sorc/hafs_gsi.fd/fix'...
ssh: Could not resolve hostname gerrit: Name or service not known
fatal: Could not read from remote repository.

**Comment by BinLiu-NOAA** [comment]
@lliu1220, The reason is that currently you probably do not have access to the GSI fix and libsrc repositories on VLAB Git. However, this will be soon resolved in the develop branch after this PR #46 being merged, which will update hafs_gsi.fd to remove its submodule dependency of libsrc and fix.

**Comment by lliu1220** [comment]
thank you @BinLiu-NOAA 
That is helpful to know.
Can you possibly add me to GSI fix and libsrc repository on VLAB Git so I could properly git clone?
Thanks.

**Comment by BinLiu-NOAA** [comment]
@lliu1220 This PR #46 has been merged back into HAFS develop branch. With that, the GSI libsrc and fix dependency is removed for HAFS. You should be able to clone/checkout the whole HAFS application package by:
git clone --recursive https://github.com/hafs-community/HAFS
Please feel free to let me know if you still have issues to clone/checkout HAFS develop branch.

BTW, if you still want to access GSI libsrc and fix repositories on VLAB, you will need to request through their VLAB pages through their code repository Admins.

**Comment by lliu1220** [comment]
thank you @BinLiu-NOAA for resolving this, i'm closing this issue.
