### ISSUE TITLE
Deal with sea ice grid points in HAFS FV3ATM-HYCOM coupling

### ISSUE THREAD

**Issue by BinLiu-NOAA** [hafs-community/HAFS#61]
HAFS FV3ATM-HYCOM coupling forecast fails when there are sea ice grid points in the regional HAFS model domain. In the current ufs-weather-model forecast, when cplflx is set .true., it assumes there will be an active sea-ice model component, which is the case for the S2S application (FV3ATM-MOM6-CICE6 coupling). But, HAFS currently only has HYCOM coupling without a sea-ice model component. 

Currently, a temporary fix (workaround) has been committed in the support/HAFS branch of https://github.com/hafs-community/ccpp-physics to deal with sea ice points properly in HAFS FV3-HYCOM coupling without the CICE6 component, following the discussions/suggestions among @junwang-noaa , @SMoorthi-emc, @ChunxiZhang-NOAA @danrosen25, @BinLiu-NOAA, etal. Detailed source code changes can be seen in [this commit](https://github.com/hafs-community/ccpp-physics/commit/9b81508da024154b5302d48162939fe9c527668e#diff-2517a4717279397b7771521de458a4c38a9c4965eb9bed4748261aebcf6ea97c).

However, a better solution would be to separate the cplflx namelist option into cplocn and cplice (like the existing cplwav) options, and use these namelist options to control the related ocean and sea-ice coupling situations. This probably will need a unified/coordinated solution among all the related coupled UFS applications (e.g., S2S, HAFS).

**Comment by panll** [comment]
Already fixed. Close and open new Issue if a better solution is identified.
