### ISSUE TITLE
Run the HWRF physics suite with Thompson microphysics with HAFS workflow

### ISSUE THREAD

**Issue by mrinalbiswas** [hafs-community/HAFS#69]
Running Thompson microphysics in an automative way using the HAFS workflow.

**Comment by BinLiu-NOAA** [comment]
@mrinalbiswas, I believe the capability of running Thompson MP (as used in HAFSv0.3S configuration) is now in the develop branch, after PR #136. So, I think we can close this issue now. Please let me know otherwise. Thanks!
