### ISSUE TITLE
Add satellite post capability and product

### ISSUE THREAD

**Issue by BinLiu-NOAA** [hafs-community/HAFS#74]
Currently, HAFS does not have satellite post products yet. Add satellite post capability and products in HAFS application workflow.

**Comment by LinZhu-NOAA** [comment]
The satellite products (GOES-R and SSMIS-F17 channels) were added in post and tested successfully. I have created a pull request in NOAA-EMC/EMC_post branch.

**Comment by BinLiu-NOAA** [comment]
@LinZhu-NOAA, Thanks for the updates! Glad to know it is working now. Once the changes in EMC_post are merged into EMC_post develop branch, please also create PR to update HAFS application/workflow level's develop branch. Thanks!

**Comment by BinLiu-NOAA** [comment]
Close issue #74 via PR #95. A note, currently the satpost is turned off by default. The inline satpost needs a new version of UPP lib, which will be installed on supported platforms end of September or Early October. After that, we can turn on satpost by default.
