### ISSUE TITLE
g2 updates(g2/3.4.3)

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [hafs-community/HAFS#78]
Due to two bugs [#63](https://github.com/NOAA-EMC/NCEPLIBS-g2/issues/63) in the g2 library(prior to the latest 3.4.3 version), hafs subcomponents (hycom_utils and vortextracker) fail with g2 from hpc-stack on certain platforms. Currently, the workaround is, use g2 from HWRF build in the vortextracker component, and point to the specific g2/3.4.1 version for hycom_utils build. The two bugs in g2 were fixed in the 3.4.3 release. Accordingly, the HAFS script and modulefile files were  updated to point g2/3.4.2 in hpc-stack in the PR (https://github.com/hafs-community/HAFS/pull/77)

**Comment by BinLiu-NOAA** [comment]
Close #78 via PR #77.
