### ISSUE TITLE
Error in writing/reading grib2 file(post jobs)

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [hafs-community/HAFS#81]
"atm_post" fails occasionally on Orion and Hera with the message:

`**** FATAL ERROR: rd_grib2_msg_seq_file, missing end section ('7777') ****"`

Normally this error is not reproducible, rewinding the relevant tasks will succeed the "atm_post".
It appears that the error occurs when the grib2 records were written, probably due to a memory issue and grib2 file is incomplete. Once the bad grib2 file is created, the error message can be duplicated by `wgrib2 (grib2file)`.

In a grib file, there is a header that provides information about the length of the record, then the record, and a "7777" signals the end of the record. The error message "missing end section ('7777)" probably indicates that the grib2 file is incomplete.

On Hera, if you run the tasks with the "bigmem" partition (large memory available), such an error is not encountered so far.

**Comment by panll** [comment]
Not currently experiencing this issue.
