### ISSUE TITLE
Change fhcyc from 24 to 0 in input.nml

### ISSUE THREAD

**Issue by BinLiu-NOAA** [hafs-community/HAFS#99]
## Description
Currently, in HAFS, fhcyc is set as 24 in input.nml. Propose to change it to 0, since HAFS focuses on hurricane weather forecasting.

## Proposed solution
Change fhcyc in input.nml from 24 to 0.

## Related to
- associated with hafs-community/HAFS/pull/<pr_number>

**Comment by evankalina** [comment]
@BinLiu-NOAA I note that the [CCPP scientific documentation](https://dtcenter.ucar.edu/GMTB/v5.0.0/sci_doc/CCPPsuite_nml_desp.html) describes fhcyc as the "frequency for surface data cycling in hours," with a default value of 0.0. While I'm not exactly sure what this parameter does, I see that the EMC CAM group is using fhcyc=0.0 in the [input.nml for their RRFS parallels](https://www.emc.ncep.noaa.gov/users/emc.campara/rrfs/namelist.html). Does this parameter have any impact over the ocean, or only over land?

**Comment by BinLiu-NOAA** [comment]
@evankalina, with the discussions @ChunxiZhang-NOAA and I had, we would also like to set fhcyc as 0 for HAFS, since HAFS mainly focuses short to medium range weather forecasts for hurricanes. And actually, using the current fhcyc value of 24 in HAFS, the regional HAFS forecast model has issues to run in the debug mode. Meanwhile, for HAFS with ocean coupling turned on, this fhcyc should not have real impacts for the ocean points (the SST values are coming from the HAFS ocean component).

**Comment by evankalina** [comment]
@BinLiu-NOAA Thanks for the additional details! The change sounds reasonable to me.

**Comment by BinLiu-NOAA** [comment]
@ChunxiZhang-NOAA, when you get a chance, could you please make this change and create a pull request to merge this change back to HAFS develop branch? Thanks! Bin

**Comment by BinLiu-NOAA** [comment]
Close this issue #99 through PR #100.
